### ISSUE TITLE
Comments by Yolanda

### ISSUE THREAD

**Issue by dgarijo** [LinkedEarth/Ontology#35]
The diagram does not show Calibration or CalibrationCurve.

I don’t understand why we need to separate Observation from MeasuredVariable.  Can we just delete Observation?  Are there other subclasses of it, so we can justify having it?

I also don’t understand how are Sensor and SensorModel related, same for Calibration and CalibrationModel, etc.

**Comment by LinkedEarth** [comment]
Will b fixed on the next commit
